### ISSUE TITLE
Different performance in different browsers. 

### ISSUE THREAD

**Issue by jacquesjbotha** [two10degrees/AzureSpeedTest#6]
I'm running this tool in both IE and Chrome simultaneously and am getting totally different results. PS. Very cool tool. Nice work.

**Comment by richorama** [comment]
Thanks for reporting the issue. I have also observed this behaviour, but I'm not sure what the cause is, or how to fix it... 

The results do seem to be consistent in order (despite the times being slower), but it would be nice if they were consistent in timings too!
