### ISSUE TITLE
2 new zones added to azure, Canada Central & Canada East

### ISSUE THREAD

**Issue by ncareau** [two10degrees/AzureSpeedTest#7]
Microsoft Azure just added 2 new zone to their infrastructure, Canada East and Canada Central.

It would be great if these zone were added to the speedtest. 

You can see the 2 new regions here : https://azure.microsoft.com/en-us/regions/

**Comment by richorama** [comment]
thanks, yes, I'd like to add them in, however, they don't show up in my portal. I need someone in Canada to create a couple of storage accounts :¬)

**Comment by ncareau** [comment]
Created both speedtestcae.blob.core.windows.net and speedtestcac.blob.core.windows.net for Canadian zone East and Central respectively.

Do i need to add files or something else ? do you know how much traffic/cost i can expect running these storage accounts ?

**Comment by richorama** [comment]
Awesome - thank you!

Could you:

* Create a container in each blob storage account called `$root`. 
* Set the access permissions to public.
* upload a file called `cb.json` to each container

The `cb.json` file should contain this text:
```
call("speedtestcae")
```
and
```
call("speedtestcac")
```
...respectively.

The cost to your azure account should be negligible. If at any time you wish to withdraw your storage accounts, let me know and I'll find an alternative.

Thanks!

**Comment by ncareau** [comment]
speedtestcac.blob.core.windows.net/cb.json
and 
speedtestcae.blob.core.windows.net/cb.json

should be working.

**Comment by richorama** [comment]
it's live, thanks for your help!
