### ISSUE TITLE
Add german regions

### ISSUE THREAD

**Issue by Tevion** [two10degrees/AzureSpeedTest#8]
Please add the two german datacenters.

https://azure.microsoft.com/en-us/blog/microsoft-azure-germany-now-available-via-first-of-its-kind-cloud-for-europe/

**Comment by richorama** [comment]
Hi @Tevion, thanks for the suggestion.

Unfortunately I'm not able to add the German data centres from my subscription, I assume you need an account in Germany :¬(

**Comment by keklabs** [comment]
From comments under the blog:
"Microsoft Azure Deutschland has a separate Portal not connected to the global environment. Hence Germany regions will not show in Portal(http://portal.azure.com)
You will require a need a German Cloud specific login to provision services in the German regions. To buy and provision services in Germany, Customers must have a billing address in EU/EFTA. If you meet the billing address in EU/EFTA requirement and want to access Germany please contact us on azuregermany@microsoft.com to onboard you to Microsoft Cloud Germany. "

**Comment by richorama** [comment]
@keklabs Thanks, does anyone have an account???
